### ISSUE TITLE
Enable EBS optimized flag on spot instances where possible

### ISSUE THREAD

**Issue by phils** [cristim/autospotting#88] opened 2017-02-26 11:55 UTC
## Issue type ##

- Feature Idea

## Summary ##

A quirk of the EC2 EBS Optimized flag is that it defaults to off, even on instances where EBS Optimized is included for free (e.g. m4, r4, c4 types, as per http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html).

When using autospotting, it may replace an instance that does not support ebs optimised, with an instance that does.  However, you can't specify EBS optimised = true on a machine that doesn't support it, so when autospotting copies the launch configuration for the spot, it brings across the lack of ebs optimisation.

Feature would be for autospotting to know which types support ebs optimised, and flag it on when possible for spot instances.

**Comment by cristim** [comment] 2017-02-26 17:26
This is a great suggestion, thanks!

We already have available in the instance type data the information about the EBS throughput and IOPS, we could use it to always choose instances that provide the same throughput and IOPS, just like we do for memory and CPU, if the optimized EBS flag is enabled or the instance has it enabled out of the box.

I noticed that the instance types that have the option of optimized EBS have those fields non-zero, while the others where optimized EBS is unavailable have them both set to zero.

Unfortunately at the moment we don't have any data about the instance types which have it enabled out of the box, and the problem is that the other instance types where it is available but disabled out of the box have an hourly surcharge when EBS is enabled. This price should be considered if we decide to enable the EBS optimized flag on those spot instance types, since it may add up to cost more than other spot instance types where it is available out of the box.

This piece of data needs to be added to ec2instances.info, and there is already a ticket for this feature: https://github.com/powdahound/ec2instances.info/issues/110

Once that is implemented we can make use of it to enable it correctly when the original instance is EBS-optimized out of the box considering the price surcharge for those instance types where it costs extra.

**Comment by cristim** [comment] 2017-02-27 00:14
I just created a pull request for adding this data in the upstream project which we use for static instance information.

We will soon be able to make use of it to implement this feature entirely.

**Comment by xlr-8** [comment] 2017-03-10 23:56
For the follow up, the PR was merged: https://github.com/powdahound/ec2instances.info/pull/231

**Comment by cristim** [comment] 2017-03-14 06:47
This should be ready for implementation, whoever is interested in this feature should feel free to pick it up.

I think this is easy enough even to be done as a first contribution to the project by a new developer.

**Comment by cristim** [comment] 2017-07-03 21:44
Closing, fixed in #114 which was just merged

**Closed by cristim** 2017-07-03 21:44 UTC
Labels: code contribution wanted, enhancement, help wanted
