### ISSUE TITLE
Failed to tag instance

### ISSUE THREAD

**Issue by roeyazroel** [cristim/autospotting#50] opened 2016-11-27 11:01 UTC
It has happened before, the waitFor function should be enough, but it's look like the request it self doesn't exists.

The instance was launch successfully with the right user data.

```
autoscaling.go:313: test-ecs-cluster Waiting for spot instance for spot instance request sir-7tag5hag
autoscaling.go:468: awseb-e-sku5tnq3xu-stack-AWSEBAutoScalingGroup-1F01KRYAGNGAD Failed to create tags for the spot instance request InvalidSpotInstanceRequestID.NotFound: The spot instance request ID 'sir-r1vi76vg' does not exist
status code: 400, request id: d00b11c4-ba27-4934-ab5e-5a189b6b1c64
```

**Comment by xlr-8** [comment] 2017-02-16 14:46
Any way to reproduce this bug?

**Comment by cristim** [comment] 2017-02-20 11:37
Could this be related to #82?

**Comment by xlr-8** [comment] 2017-02-20 11:50
I think this was introduced later on, so it might not be related. But with the lack of information it's hard to say / reproduce.

**Comment by cristim** [comment] 2017-03-30 09:21
@roeyazroel please try a more recent build and see if you can still reproduce this.

**Comment by cristim** [comment] 2017-04-07 15:07
Closing this due to lack of information on how to reproduce it.

We can re-open if it shows up again and we have clear ways to reproduce it.

**Comment by dvinograd** [comment] 2017-10-02 22:00
Hi @cristim,

We seem to be experiencing this issue in our setup. We've set up lambda last week in us-east-1 with the following settings:

```
ExecutionFrequency | rate(5 minutes)
LambdaHandlerFunction | handler.Handle
LambdaMemorySize | 256
LambdaS3Bucket | cloudprowess
LambdaZipPath | dv/lambda.zip
LogRetentionPeriod | 14
MinOnDemandNumber | 0
MinOnDemandPercentage | 0.0
Regions | us-east-1 us-west-2
```

It works as expected in us-east-1. However in us-west-2 it's failing to tag and attach newly provisioned spot instances to autoscaling group so they're left running without being utilized (we've manually terminated 72 spot instances in this state).

The error in logs is:

```
2017/10/02 21:34:52 autoscaling.go:582: Bidding for spot instance for Edmunds-QA-21-ECS-Cluster-QA21ECSAutoScaleGroup-18S8T7WLPUZH2
2017/10/02 21:34:53 autoscaling.go:620: Edmunds-QA-21-ECS-Cluster-QA21ECSAutoScaleGroup-18S8T7WLPUZH2 Created spot instance request sir-6ew89dcp
2017/10/02 21:34:53 spot_instance_request.go:107: Edmunds-QA-21-ECS-Cluster-QA21ECSAutoScaleGroup-18S8T7WLPUZH2 Failed to create tags for the spot instance request sir-6ew89dcp retrying in 5 seconds...
END RequestId: 388c817b-a7b9-11e7-82a8-cd06f7130e47
```

It would be helpful to see why it failed to create tags (is there a permission issue?) - would it be possible to include more log output?

**Comment by xlr-8** [comment] 2017-10-03 09:02
Hi, thanks for reporting it! You could try to check: https://github.com/cristim/autospotting/issues/109 ? That might provide more inputs, if not we need to add some more debug logs.

**Comment by dvinograd** [comment] 2017-10-04 08:32
@cristim @xlr-8 Thanks guys, we'll try these steps to provide additional debug info sometime this week, and will keep this thread updated. And no worries about those untagged spot instances. Side story, we've had a similar experience with Opsworks Stacks layer 'auto healing' feature, side effect of which was creating more and more on-demand VMs quite rapidly.. and that's an AWS product.

**Comment by roeyazroel** [comment] 2017-10-17 17:51
@cristim I think we can close this issue, since the "retry" fix i didn't see this issue again.

**Comment by cristim** [comment] 2017-10-17 21:29
@roeyazroel I agree.

@dvinograd, please reopen in case you have to add anything to this issue.

**Closed by cristim** 2017-10-17 21:29 UTC
Labels: bug, help wanted, need information
