### ISSUE TITLE
Keep at least one (or more) reserved instance running

### ISSUE THREAD

**Issue by seme1** [cristim/autospotting#21] opened 2016-09-29 19:45 UTC
I have a web application and it is essential to have a number of instances always running to handle the possibility of having all spot instances shut down and make the web application still accessible. 

Is it possible to configure Autospotting to keep a specific (or a number of) reserved instances without replacement while replacing the rest of the instances with spot ones ?

**Comment by cristim** [comment] 2016-09-30 07:36
Thanks for reporting this.

It looks like a duplicate of #10, but we can discuss this here, because we have better context in the content of the issue.

Honestly I think that even a small number of on-demand(and even reserved) instances may cost you as much as the entire rest of the group running on spot instances, and in case all those spot instances are terminated, the remaining reserved/on-demand capacity is likely to be insufficient for many use cases, at least for a short while.

AutoSpotting already does a lot to reduce the risk of termination for all your spot instances, by spreading them over multiple instance types on each availability zone when it can get dangerous, but I've seen this question being asked a lot so I will have to implement it somehow, and it's actually the next thing I plan to do.

I realize that there are so many use cases out there and if possible it's better to accommodate more of them and let the users decide how to use it. For that, I need to make autospotting configurable, so that everyone can enable/disable such optional functionality and tweak it as per their needs. This is already tracked as #5, we can discuss that aspect there if you would like. But once I make it configurable, I can relatively easily implement this functionality.

**Comment by schodemeiss** [comment] 2016-09-30 13:40
+1 for this functionality. Just a min configurable for the amount of EC2's to leave in on-demand would be great.

**Comment by seme1** [comment] 2016-09-30 14:05
@cristim Thanks for the response. I'd rather be ready for the worst case scenario (when all spot instances are terminated) by having a slow service (or with lots of timeouts) than having a completely non-functioning/offline service.

**Comment by cristim** [comment] 2016-09-30 14:32
@seme1 ideally you should have a multi-region setup so that a single region failure would not be catastrophic, but I can understand your point.

As I said, I will implement this functionality soon, I just need to implement the configuration mechanism first, please bear with me.

In the meantime, if you really need this functionality now, it's actually pretty easy to fork autospotting and build your own version that implements this functionality in just a few lines of code. Have a look in core/autoscaling.go, around line 800 where we count the current number of spot instances.

You basically need exit that loop if that number is too close to the group's total capacity, it's a simple subtraction followed by an if statement. You can also make it percentage-wise with just a few more lines.

You will also need an S3 bucket where to deploy the forked builds, and deploy your CloudFormation stack based on that bucket.

All in all, shouldn't take more than a couple of hours of work.

**Comment by cristim** [comment] 2016-12-21 23:27
I think #54 implements enough functionality to consider this resolved.

**Closed by cristim** 2016-12-21 23:27 UTC
Labels: Epic

**Comment by cristim** [comment] 2016-12-23 22:05
@seme1, @schodemeiss we now have support for this thanks to @xlr-8's contribution.

Please give it a try and give us some feedback.
